### ISSUE TITLE
Sometimes crash on low-end android devices

### ISSUE THREAD

**Issue by qngnht** [floatinghotpot/cordova-admob-pro#145]
Hi , I have a problem with Interstitial ad. After It loaded, showed and closed. It is still there, my question is how can I destroy it ? Because it take too much image memory which make my app crash so often in some weak android devices, I just found this bug in 2 days ago and lost so many customers because of it >.< I saw removeBanner() function, does it work for Interstitial ad ? Thank you so much.
P/S : This bug is only on real mode. Test mode works perfectly.

**Comment by qngnht** [comment]
I found many topics on lots of forum , they all have same issue and seems no clue to fix it... or I did't find it yet ...

**Comment by floatinghotpot** [comment]
The admob interstitial object is a one-time object, once it's dismissed (when user click X to close it), it will be destroyed automatically.

As to when the memory will be released, it will be depends on the JVM garbage collection settings.

**Comment by qngnht** [comment]
Sorry for the title of the topic, because I didn't know exactly what the problem is. I'm still looking for the solution to fix it.

**Comment by floatinghotpot** [comment]
Why you think it's cause by AdMob Ads? Any crash error report, logs or analysis as evidence or clues?

**Comment by qngnht** [comment]
Because I tested it in many ways, test mode is perfect, nothings happened. The real mode cause the fps of the game dropped in few seconds and make app closed or crashed if the device is really weak, as my testing device Dragon Touch Y88, or some vdevices have 512 mb. Many forum reported it as Admob ad bug. I just found a solution is choose the ad to show as text or image only to fix this. i

**Comment by qngnht** [comment]
I found it here https://shatter-box.com/knowledgebase/troubleshooting/  Fix lags Admob plugin. I'm testing it.

**Comment by floatinghotpot** [comment]
I see. It might be when admob sdk loading resource from server. Using text ad only may reduce the risk of crash as less resource required.

**Comment by qngnht** [comment]
The fps drop happened only after the ad is showed and closed.

**Comment by qngnht** [comment]
It goes completely well now. Follow above instruction fixed it. I checked to show Image ad only, and uncheck text ad in Setting of the Admob ad.

**Comment by floatinghotpot** [comment]
Nice to hear that your issue is resolved. I think the experience is useful to other guys too. Thanks.

**Comment by qngnht** [comment]
Hi Raymond, today I tried to run my ad with low battery on same my testing Android tablet, the bug is still there. No idea >< I think it isn't resolved with above config.

**Comment by qngnht** [comment]
The game has crashed many times I tried today.

**Comment by qngnht** [comment]
The ad is keep loading after closed. I think somethings happened with adView.stopLoading();  function. I need to figure it out ...
