### ISSUE TITLE
Multiple DEX files error

### ISSUE THREAD

**Issue by slikk66** [floatinghotpot/cordova-admob-pro#512]
Can someone please give a proper answer for this other than "you're using another plugin".

When adding in admob, this error appears.

Before adding in admob:
```
BUILD SUCCESSFUL

Total time: 4.805 secs

Built the following apk(s):
        /PathToApp/platforms/android/build/outputs/apk/android-debug.apk
```

Then:
`$ ionic plugin add cordova-plugin-admobpro`

After adding, build gives:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by slikk66** [comment]
Any steps to determine which plugin is causing the error, and then also how to fix this issue?  Is the only way to fix it by not using admob with the other plugin?  Is it possible to use both of them together?

Can someone give specific answer as to what is causing this error and how to avoid it moving forward?  Seems this is a fairly common thing searching for the issues but besides small bandaids on how to possibly fix a one time collision, I can't find any definitive answers.

**Comment by floatinghotpot** [comment]
please run `cordova plugin ls`, then copy/paste the listed plugins here, so we can tell which plugin may cause conflict.

**Comment by slikk66** [comment]
```
com.colibrisoftware.plugins.backgroundjs 3.3 "BackgroundJS"
com.ionic.keyboard 1.0.4 "Keyboard"
com.metacube.metacampus.mediarefresher 0.0.1 "Media Refresher"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-file-transfer 1.3.0 "File Transfer"
cordova-plugin-inappbrowser 1.0.1-dev "InAppBrowser"
cordova-plugin-media 1.0.1 "Media"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-whitelist 1.0.1-dev "Whitelist"
cordova-plugin-x-toast 2.2.1 "Toast"
nl.x-services.plugins.backgroundaudio 1.0.1 "BackgroundAudio"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.jshybugger.cordova 4.5.9 "jsHybugger"
```

**Comment by slikk66** [comment]
How can I see what dependencies that these plugins have?  Using ionic/cordova in past, I've never had to delve into the dependencies, and I do all my work from command line, I don't use Android studio.

**Comment by floatinghotpot** [comment]
I see the conflict `Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode`, it means another plugin also include the admob sdk jar in it, and cause conflict with AdMob SDK.

I attempt to identify which plugin contains such a jar. But I cannot found some of the plugins in your list in either npm or cordova plugin registry https://cordova.apache.org/plugins/ . 

BTW, according to cordova team, all cordova plugins should be migrated to npm, and named in rule `cordova-plugin-xxx`, like this:
https://www.npmjs.com/package/cordova-plugin-admobpro

So hard to find their github repo to check further details. Can you give me github repo URL of each plugin, if it cannot be found in npm?

**Comment by floatinghotpot** [comment]
no more reply, i suppose this issue has been resolved.

**Comment by slikk66** [comment]
I haven't been able to find and analyze all of the other plugins to find why it breaks when adding admob, so I've decided to not use admob plugin.

**Comment by fidoafif** [comment]
@floatinghotpot  Hi, this not resolved yet, I try and give me the same error
