### ISSUE TITLE
 Support iOS 8

### ISSUE THREAD

**Issue by devalexqt** [floatinghotpot/cordova-admob-pro#79]
I in debug console my app prompt next message:
So its don't support iOS 8?
```
<Google:HTML> 
You are currently using version 6.12.0 of the SDK, which doesn't officially support iOS 8. Please consider updating your SDK to the most recent sdk version, 6.12.2, to get iOS 8 support, including a fix for smart banner rendering in landscape mode. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/mobile-ads-sdk/docs/admob/ios/rel-notes.
```

**Comment by floatinghotpot** [comment]
It has been upgraded to v6.12.2 in Nov 2014, see commit:
https://github.com/floatinghotpot/cordova-admob-pro/commit/a73b11f94be257d7a77206aaa490fab001a7a1b8

I double checked the binary .a file, it's same size: 13,403,052 bytes.

are you using an old version?

**Comment by sean-hill** [comment]
Hey I just downloaded this plugin and am getting this warning:

	You are currently using version 7.0.0 of the SDK, which doesn't officially support iOS 8. Please consider updating your SDK to the most recent sdk version, 7.1.0, to get iOS 8 support, including a fix for smart banner rendering in landscape mode. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/mobile-ads-sdk/docs/admob/ios/rel-notes.

Is it not updated?

**Comment by floatinghotpot** [comment]
but it's already upgraded to v7.1.0, see: 30817fac8f80993bb38a24d97b94214ff5c26fe4

**Comment by sean-hill** [comment]
Weird, is the version in the Cordova registry outdated? I could try adding the plugin directly from GitHub if that'll work.

**Comment by floatinghotpot** [comment]
you are correct, i forgot to publish it to cordova registry... now it's being published as v2.7.5

**Comment by floatinghotpot** [comment]
wait a few minutes ...

**Comment by sean-hill** [comment]
Wahoo! Thanks :smile:

**Comment by floatinghotpot** [comment]
done.

**Comment by sean-hill** [comment]
Hey @floatinghotpot, I just tried this morning with

    cordova plugin rm com.google.cordova.admob
    cordova plugin add com.google.cordova.admob

But I'm still getting the same message when I launch Admob in my app about it not being compatible with iOS 8.

**Comment by sean-hill** [comment]
Opening the `plugin.xml` shows that it is still `version="2.7.4"`.

**Comment by floatinghotpot** [comment]
i've tried to install the admob plugin and the plugin.xml is 2.7.5

try:
1. remove the cache from your home: ~/.plugman/cache
2. type "cordova plugin remove xxx", instead of "plugman plugin rm xxx", though i am not quite sure...

**Comment by sean-hill** [comment]
Hey @floatinghotpot! Good news. After clearing the plugman cache, the plugin installed the latest. Thanks! Silly caches... :smile:
